const types = {
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT: 'COUNTER_DECREMENT',
  COUNTER_RESET: 'COUNTER_RESET',
  COUNTER_UPDATE_MARGIN: 'COUNTER_UPDATE_MARGIN',
};

export default types;
